### ISSUE TITLE
Callbacks not working

### ISSUE THREAD

**Issue by JobGetabu** [maltaisn/recurpickerlib#7]
the callbacks are not being called.
 ```
@Override
    public void onRecurrencePickerSelected(Recurrence r) {
        Toast.makeText(activity, "working", Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onRecurrencePickerCancelled(Recurrence r) {

        Toast.makeText(activity, "dismissed", Toast.LENGTH_SHORT).show();
    }
```

**Comment by JobGetabu** [comment]
They don't return in fragments. 
Only works in activities.

**Comment by maltaisn** [comment]
This should be fixed in 1.2.6, but I didn't test it so please confirm.
Don't forget to call `setTargetFragment(fragment)` on the dialog. Sorry for the late reply by the way.

**Comment by JobGetabu** [comment]
still doesn't works on fragments
or what does `setTargetFragment(fragment, requestCode)` actually do ? and which fragment is passed in ?

**Comment by maltaisn** [comment]
You have to call `setTargetFragment` so that the picker knows what fragment to call back to. So pass in the fragment that is receiving the result.
